apiVersion: v1
kind: Service
metadata:
  name: {{ include "opencamunda.zeebe.clusterName" . }}
  labels:
    {{- include "opencamunda.zeebe.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  type: {{ .Values.zeebe.service.type }}
  ports:
    - port: {{ .Values.zeebe.service.httpPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.zeebe.service.commandPort }}
      protocol: TCP
      name: command
    - port: {{ .Values.zeebe.service.internalPort }}
      protocol: TCP
      name: internal
    {{- if .Values.zeebe.embeddedGateway }}
    - port: {{ .Values.zeebe.service.gatewayPort }}
      protocol: TCP
      name: gateway
    {{- end }}
  selector:
    app.kubernetes.io/component: zeebe-broker
    app.kubernetes.io/instance: {{ .Release.Name }}
---
{{- if .Values.zeebe.embeddedGateway }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opencamunda.zeebe.clusterName" . }}-gateway
  labels:
    {{- include "opencamunda.zeebe.labels" . | nindent 4 }}
spec:
  type: {{ .Values.zeebe.service.type }}
  ports:
    - port: {{ .Values.zeebe.service.gatewayPort }}
      protocol: TCP
      name: gateway
      targetPort: {{ .Values.zeebe.service.gatewayPort }}
    - port: 8080
      protocol: TCP
      name: rest
      targetPort: 8080
    - port: {{ .Values.zeebe.service.httpPort }}
      protocol: TCP
      name: http
      targetPort: {{ .Values.zeebe.service.httpPort }}
  selector:
    app.kubernetes.io/component: zeebe-broker
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
