{
 "title": "Zeebe Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(atomix_role, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(atomix_role{cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(atomix_role{cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "partition",
    "query": {
     "query": "label_values(atomix_role{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}, partition)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Health",
   "type": "table",
   "description": "Shows health per partition and pod",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "zeebe_health{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"} ",
     "legendFormat": "Partition {{pod}} {{partition}}"
    },
    {
     "expr": "atomix_role{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"} "
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "timeseries",
   "description": "Shows when and how often a pod was restarted.  The graph is zero when the pod is ready. With this it is also possible to determine how long it take for the pod to come ready again.",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "1 - kube_pod_container_status_ready{pod=~\"$pod\", cluster=~\"$cluster\", container!~\"curator|curl\", namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}} restart"
    }
   ]
  },
  {
   "title": "Role changes over time",
   "type": "graph",
   "description": "Shows when a role change has happened. \n1 = Follower\n2 = Candidate\n3 = Leader\n2 - ",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Role (3 = Leader)" }
   ],
   "targets": [
    {
     "expr": "atomix_role{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}",
     "legendFormat": "{{pod}} p{{partition}} "
    }
   ]
  },
  {
   "title": "Pod Last Terminated Reason",
   "type": "table",
   "description": "Shows the reason for the last pod restart",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"zeebe\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Backpressure Dropping Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(zeebe_dropped_request_count_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) by (partition) / sum(rate(zeebe_received_request_count_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[$__rate_interval])) by (partition) ) * 100",
     "legendFormat": "Partition {{partition}}"
    },
    {}
   ]
  },
  {
   "title": "Processing per Partition",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zeebe_stream_processor_records_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", action=~\"skipped|processed\"}[$__rate_interval])) by (pod, partition, processor)",
     "legendFormat": "{{pod}}-{{partition}}-{{processor}}-processed"
    },
    {
     "expr": "sum(rate(zeebe_stream_processor_records_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", action=~\"written\"}[$__rate_interval])) by (pod, partition, processor)",
     "legendFormat": "{{pod}}-{{partition}}-{{processor}}-written"
    }
   ]
  },
  {
   "title": "Overall FNI  per s",
   "type": "stat",
   "description": "Flow node instances completed or terminated per second over all partitions.",
   "gridPos": { "h": 2, "w": 9, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", type!=\"PROCESS\", action!=\"activated\"}[$__rate_interval]))",
     "legendFormat": "Partition {{partition}} FNI per s"
    }
   ]
  },
  {
   "title": "Exporting per Partition",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zeebe_exporter_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (pod, partition, exporter)",
     "legendFormat": "{{pod}}-{{partition}}-exported"
    }
   ]
  },
  {
   "title": "Completed Tasks in avg overtime per sec",
   "type": "stat",
   "description": "Takes the avg of all completed tasks per second over the given time range.",
   "gridPos": { "h": 2, "w": 9, "x": 7, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", action=\"completed\", type=\"SERVICE_TASK\"}[$__rate_interval]))",
     "legendFormat": "{{type}} {{action}}"
    }
   ]
  },
  {
   "title": "Completed Processes in avg overtime per sec",
   "type": "stat",
   "description": "Takes the avg of all completed processes per second over the given time range.",
   "gridPos": { "h": 2, "w": 9, "x": 7, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", action=\"completed\", type=\"PROCESS\"}[$__rate_interval]))",
     "legendFormat": "{{type}} {{action}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{job=\"kubelet\", cluster=~\"$cluster\", namespace=~\"$namespace\", image!=\"\", pod_name=~\"$pod\", container_name!=\"POD\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Requests handled by Gateway per sec",
   "type": "graph",
   "description": "Shows which requests have hit the gateway and which response have been sent to the client (per second).",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(label_replace(rate(grpc_server_handled_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]), \"method\", \"$1\", \"grpc_method\", \"(.+)\"), \"statusCode\", \"$1\", \"code\", \"(.+)\") or rate(grpc_server_processing_duration_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) by (method, statusCode)",
     "legendFormat": "{{method}} Request ({{statusCode}})"
    }
   ]
  },
  {
   "title": "Process memory usage",
   "type": "graph",
   "description": "Memory limits and requests are taken from the k8 pod metrics.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_rss{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", container=~\"zeebe.*\"}",
     "legendFormat": "{{pod}} RSS"
    },
    {
     "expr": "max(kube_pod_container_resource_limits_memory_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", container=~\"zeebe.*\"})",
     "legendFormat": "limit"
    },
    {
     "expr": "min(kube_pod_container_resource_requests_memory_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", container=~\"zeebe.*\"})",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Zeebe Broker Disk usage",
   "type": "graph",
   "description": "Shows how much disk is used by each broker.",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 29 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(kubelet_volume_stats_used_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", persistentvolumeclaim=~\".*zeebe.*\"} / kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", persistentvolumeclaim=~\".*zeebe.*\"})",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}